### ISSUE TITLE
CC3200, non-launchpad: ftdi_usb_open failed

### ISSUE THREAD

**Issue by kzyapkov** [cesanta/mongoose-flashing-tool#4]
When a CC3200 device is hooked through a USB-serial chip which is different from the JTAG-enabled one on the CC3200 launchpad, FNC fails with "ftdi_usb_open failed". 

I think it should prompt the user for SOP2 and reset and try to talk to the bootloader anyway.

**Comment by rojer** [comment]
yep, makes sense

**Comment by rojer** [comment]
can you re-test with this commit please? it should make use of libftdi best-effort.

**Comment by kzyapkov** [comment]
Works fine with other FTDI chips and non-FTDI usb-serial adapters.
